# Generated by Django 6.0.4 on 2026-05-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_event_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_number',
            field=models.IntegerField(default=0, verbose_name='Номер брони у пользователя'),
        ),
    ]
